---
title: "R Notebook"
output: html_notebook
---

# Mountain Rescue Incident Data

This is a repository of mountain rescue incident data, along with the associated web scraping scripts. It's written in R. It's also a work in progress.

Mountain rescue teams like to report their incidents on their websites. Some of these are run-of-the-mill ones of walkers breaking their ankles, and some are harrowing accounts of helicopters plucking cragfast and terrified students off the sheer sides of mountains in Wales.

There are 49 mountain rescue teams in the UK, each is it's own charity. You would think that there's an economy of scale for local charities to save money on website hosting, design and management costs - but you'd be wrong. This means there are 49 different websites. You'd also think that for something as simple as incident reports, there couldn't possibly be more than a handful of ways that these reports are structured. You'd also be wrong about this. Finally, you'd think that even within a single team, there'd at *least* be a consistent format or convention that locations, dates, times and incidents would conform to, and you'd be right. Some of the time.

## Teams scraped so far

- Edale
- Keswick
- Ogwen
- Patterdale
- Kendal
